server {
  listen 80;

  # frontend (React build)
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri /index.html;
  }

  # backend (NO rewrite)
  location /api/ {
    proxy_pass http://backend:5000;
  }

  # ai-service (WITH rewrite)
  location /ai/ {
    rewrite ^/ai/(.*) /$1 break;
    proxy_pass http://ai-service:8000;
  }
}